# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "FAUCET Conference and FAUCET PlugFest 2017"
email: "conference@faucet.nz"
description: "The first FAUCET conference and second FAUCET PlugFest will be held at Lawrence Berkeley National Laboratory from 18 to 20 October 2017. We will cover the operational advantages of SDN and FAUCET and examine some of the technical challenges of SDN development and how FAUCET is approaching them."
baseurl: "/"
url: "http://conference.faucet.nz"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "FAUCET Foundation"
organizerAlternateName: "FAUCET Foundation"
organizerDescription: ""
organizerEmail: "foundation@faucet.org.nz"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://faucet.org.nz/"

# Head
metaKeywords: "faucet, faucetcon, plugfest, openflow, sdn"
twitterAccount: "@faucetsdn"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://conference.faucet.nz/blog/call-for-presentations"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/speakers/", text: "Speakers"}
bottomNavigationLinks:
 - {link: "http://conference.faucet.nz/blog/call-for-presentations", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "http://conference.faucet.nz/blog/call-for-presentations", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "FAUCET Conference & FAUCET PlugFest"
eventDate: "October 18th-20th, 2017"
typeoutTextValues: ''
typeoutFallback: ""
heroButtons:
 - {link: "http://conference.faucet.nz/blog/call-for-presentations", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Get tickets"}

# About Block
aboutTitle: "About FAUCET Conference"
aboutBlock:
 - {title: "PlugFest", image: "hackathon.jpg", text: "Full-day PlugFest on Wednesday to demonstrate interoperability with Faucet." }
 - {title: "Strategic & Operational Stream", image: "conference.jpg", text: "The focus will be on the operational advantages of SDN and FAUCET. This will feature a keynote presentation from Brad Cowie of The University of Waikato on their multi-vendor FAUCET deployment." }
 - {title: "Technical & Development Stream", image: "workshop.jpg", text: "Examine some of the technical challenges of SDN development and how FAUCET is approaching them." }

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Berkeley Lab"
eventLocationLink: "https://www.lbl.gov"
eventStreetAddress: "1 Cyclotron Rd"
eventAddressLocality: "Berkeley"
eventAddressLocalityRegion: "California"
eventPostalCode: "94720"
eventAddressCountry: "USA"
eventStartTime: "2017-10-19T09:00"
eventDoorTime: "08:30"
eventEndTime: "2017-10-20T17:00"
eventPlaceCoordinates: "37.8759277, -122.2500274"
mapCenterCoordinates: "37.8759277, -122.2500274"
mapMobileCenterCoordinates: "37.8759277, -122.2500274"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: 'Tickets for both the main conference and plugfest are available for free on <a href="https://www.eventbrite.com/e/faucetcon-and-faucet-plugfest-fall-2017-registration-37054421773">EventBrite</a>.'
ticketsOffers:

# Accommodation Block
accommodationTitle: "Accommodation"
accommodationInfo: 'There is an accommodation deal for the conference at the Berkeley Lab Guest House. Note that there is a limited number of rooms so book early. Booking details are available in our <a href="/assets/faucet_conference_plugfest_accommodation.pdf">conference accommodation booking flyer</a>.'

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=faucetsdn", icon: "twitter"}
 - {link: "https://www.youtube.com/channel/UChRZ5O2diT7QREazfQX0stQ", icon: "youtube"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://faucet.nz", text: "faucet.nz"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:conference@faucet.nz", text: "conference@faucet.nz"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "faucetcon"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "PlugFest"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "PlugFest details"
hackathonRows:

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Berkeley Lab"
hackathonLocationLink: "https://www.lbl.gov"
hackathonStreetAddress: "1 Cyclotron Rd"
hackathonAddressLocality: "Berkeley"
hackathonAddressLocalityRegion: "California"
hackathonPostalCode: "94720"
hackathonAddressCountry: "USA"
hackathonTimeTitle: "Event runs from"
hackathonStartTime: "2017-10-18T09:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2017-10-18T17:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "37.8759277, -122.2500274"
hackathonMapCenterCoordinates: "37.8759277, -122.2500274"
hackathonMapMobileCenterCoordinates: "37.8759277, -122.2500274"
